# Generated by Django 4.2.24 on 2025-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(blank=True, choices=[('receipt', 'Receipt'), ('contract', 'Contract'), ('statement', 'Statement'), ('other', 'Other')], max_length=20)),
                ('document_id', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('amount_value', models.CharField(blank=True, max_length=100)),
                ('amount_currency', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
