# Generated by Django 4.2.24 on 2025-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='account_number',
            new_name='entity1_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='bank_name',
            new_name='entity2_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='client_name',
        ),
        migrations.AddField(
            model_name='document',
            name='entity1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='entity1_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='entity2_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='entity2_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
